# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6968f28ac26866b3668cb2089fe916ae989553fc876126363479d34746f580d1dae6be88c652af882fa43afa5aa12376c6dc51fd69c018396671bef58a786772

test:
  secret_key_base: b2a17a80788b7b49037ed2e0c59af89210bf94776ed2e8775e3471bd2b549c4aa83e7179d25fd96bc0e977fe56965e3b4b6564d5d9a9b533bb799c9568c0d8bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
